---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: resource-git-cookbook_api

run:
  path: resource-git-cookbook_api/ci/tasks/run-test.sh
