---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: resource-git-cookbook_api
- name: current-app-info

run:
  path: resource-git-cookbook_api/ci/tasks/update-routes.sh